name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo ci/install.sh

    - name: Build
      run: ci/build.sh

    - name: Setup loopback LIO iSCSI target
      run: |
        sudo ci/lio_setup.sh
        # dump any LIO messages
        sudo dmesg --console-level info
